### ISSUE TITLE
AddDice in DieSet class

### ISSUE THREAD

**Issue by AtkinsJM** [walpoles93/dungeons-dice#2]
The _AddDice_ method in the _DieSet_ class might take as a parameter either a single instance of the _Die_ class or an array, which should be added to the end of the _die_ array on a _DieSet_ instance. Currently the passed parameter is being iterated over and each individual _Die_ instance push onto the end of the _die_ array for the instance. Would _concat()_ work better to combine the arrays?

**Comment by walpoles93** [comment]
I think concat is probably more efficient - although for such small arrays the difference is going to be negligible.
